receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  filelog:
    include: [ "/app/logs/*.log" ]
    exclude: [ ]
    start_at: "beginning"
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'
        severity:
          parse_from: attributes.level
processors:
  batch:
    timeout: 5s
connectors:
  datadog/connector:
exporters:
  datadog/exporter:
    api:
      key: ${DD_API_KEY}
      site: "datadoghq.eu"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/connector, datadog/exporter]
    metrics:
      receivers: [datadog/connector, otlp]
      processors: [batch]
      exporters: [datadog/exporter]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [datadog/exporter]