name: Deploy Datadog Monitors

on:
  workflow_dispatch:
  push:
    paths:
      - 'monitors/*.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd .github/actions/create-monitor-action
          npm install

      - name: Create or update Datadog monitors
        uses: ./.github/actions/create-monitor-action
        with:
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DD_APP_KEY }}
          MONITOR_DIR: 'monitors'
